"""added image path

Revision ID: 01d5841e9ff2
Revises: bcbd1ccabed3
Create Date: 2026-10-07 12:41:28.169147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d5841e9ff2'
down_revision: Union[str, Sequence[str], None] = 'bcbd1ccabed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_versions', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_versions', 'image_path')
    # ### end Alembic commands ###
